[tool.poetry]
name = "transitmatters-gtfs"
version = "0.1.0"
description = ""
authors = ["Ian Reynolds <idreyn@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.2"
tqdm = "^4.65.0"
SQLAlchemy = "^2.0.7"

[tool.poetry.dev-dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
